name = "revent-task-workspace"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "revent-production-db"
database_id = "36a1f4af-6138-4966-bf28-7fc371f5eef7"

[vars]
NODE_ENV = "production"
JWT_SECRET = "revent-secure-jwt-production-edge-token-2026"
